apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-java-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-java-app
  template:
    metadata:
      labels:
        app: hello-java-app
    spec:
      containers:
        - name: hello-java-container
          image: vaeshnavipatel/hello-java-app:latest
          args: ["vaeshnavi"]
